// Generated by CoffeeScript 1.7.1
(function() {
  var subscribe_to_channel;

  angular.module('cirque', ['ui.bootstrap', 'ngGrid']);

  window.sock = new SockJS('http://localhost:8080/messages/cirque_websocket');

  subscribe_to_channel = function(channel_address) {
    var data;
    data = {
      hx_subscribe: channel_address
    };
    return window.sock.send(JSON.stringify(data));
  };

  window.sock.onopen = function() {
    return subscribe_to_channel("log-debug");
  };

  window.sock.onmessage = function(payload) {
    var dataObj;
    dataObj = JSON.parse(payload.data);
    if (dataObj.hasOwnProperty('setup_connection')) {
      console.log('Connection established.', dataObj);
    }
    if (dataObj.subject_id === "log-debug") {
      return logScope.consume_log(dataObj.message);
    }
  };

  window.Peers = function($scope) {
    return $scope.peers = [];
  };

  window.Logs = function($scope) {
    window.logScope = $scope;
    $scope.log_entries = [];
    $scope.gridOptions = {
      data: 'log_entries'
    };
    return $scope.consume_log = function(logObj) {
      console.log("Adding another row!");
      $scope.log_entries.push(logObj);
      return $scope.apply();
    };
  };

  window.Alert = function($scope) {
    return $scope.alerts = [];
  };

  window.Tabs = function($scope) {
    return $scope.tabs = [];
  };

  window.Table = function($scope) {
    return $scope.gridOptions = {};
  };

}).call(this);
